services:
  postgresql:
    container_name: postgresql
    image: postgres:17.10
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - postgres_network
      - electronics-store_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin:REL-9_13
    depends_on:
      - postgresql
    env_file:
      - .env
    ports:
      - 5433:5433
    networks:
      - postgres_network
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
      - pgadmin_config_dir:/pgadmin4
  redis:
    image: redis:7.4-alpine
#    healthcheck:
#      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
#      interval: 1s
#      timeout: 3s
#      retries: 5
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    ports:
      - 6379:6379
    networks:
      - redis_network
  redis-insight:
    image: redis/redisinsight:3.4
    ports:
      - 5540:5540
    networks:
      - redis_network
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka_network
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - kafka_network
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.4
    networks:
      - kafka_network
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:9097'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
    ports:
      - 9097:9097
  akhq:
    image: tchiotludo/akhq:latest
    networks:
      - kafka_network
    ports:
      - 9093:8080
    depends_on:
      - kafka
      - schema-registry
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: true
            authentication: cookie
            token:
              jwt:
                signatures:
                  secret:
                    generator:
                      secret: "some-random-secret-key-minimum-46-characters!!"
        akhq:
          security:
            default-group: no-roles
            roles:
              registry-admin:
                - resources: [ "SCHEMA" ]
                  actions: [ "READ", "CREATE", "UPDATE", "DELETE", "DELETE_VERSION" ]
            groups:
              schema-write:
                - role: registry-admin
            basic-auth:
              - username: schemadev
                password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
                passwordHash: SHA256
                groups:
                  - schema-write
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:9097"
#  cart-service:
#    depends_on:
#      redis:
#        condition: service_healthy

networks:
  electronics-store_network:
    external: true
    driver: bridge
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge
  kafka_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_working_dir:
    driver: local
  pgadmin_config_dir:
    driver: local
  redis-insight-data:
    driver: local