spring.application.name=electronics-store-bff
server.port=8084

spring.cloud.openfeign.client.config.productClient.url=http://localhost:8080/
spring.cloud.openfeign.client.config.cartClient.url=http://localhost:8081/
spring.cloud.openfeign.client.config.orderClient.url=http://localhost:8082/
#spring.cloud.openfeign.circuitbreaker.enabled=true