spring.application.name=order-service
server.port=8082

# feign client configuration -> connect to cart-service
spring.cloud.openfeign.client.config.cartServiceClient.url=http://localhost:8081/
spring.cloud.openfeign.circuitbreaker.enabled=true

# postgres db config
spring.datasource.url=${DB_URL}/order_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# liquibase config
spring.liquibase.enabled=true
spring.liquibase.changelog=classpath:liquibase/order_db_changelog_master.yaml

# kafka config
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
order-service.created-orders-topic=created-orders