spring.application.name=cart-service
server.port=8081

# feign client
spring.cloud.openfeign.client.config.productClient.url=http://localhost:8080/
spring.cloud.openfeign.circuitbreaker.enabled=true

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASS}

# cart-service environment variables
cart.cart-prefix=cart:
cart.ttl-hours=24