spring.application.name=product-service
server.port=8080

# postgres db config
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# liquibase
spring.liquibase.enabled=true
spring.liquibase.changelog=classpath:liquibase/db_changelog_master.yaml